insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Avenida General Norton de Matos", "1495", 135, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Cândido de Figueiredo", "1500", 010, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Alameda Fernão Lopes", "1495", 169, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Abrantes Ferrão", "1600", 177, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Aboim Ascensão", "1700", 107, "Lisboa", "Lisboa", "Alvalade", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praceta A à Avenida Cidade Lourenço Marques", 1800, 033, "Lisboa", "Lisboa", "Parque das Nações", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Actor Isidoro", 1900, 190, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Acácio Barreiro", 1950, 172, "Lisboa", "Lisboa", "Marvilla", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Passeio das Musas", 1990, 122, "Lisboa", "Lisboa", "Parque das Nações", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Actor Epifânio", 1750, 124, "Lisboa", "Lisboa", "Lumiar", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Agostinho Neto", 1750, 315, "Lisboa", "Lisboa", "Lumiar", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Estrada de Benfica", 1500, 999, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Major Afonso Palla", 1495, 475, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Calçada da Boa-Hora", 1300, 155, "Lisboa", "Lisboa", "Alcântara", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praça Afonso do Paço", 1350, 116, "Lisboa", "Lisboa", "Campo de Ourique", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praça das Águas Livres ", 1250, 170, "Lisboa", "Lisboa", "Campo de Ourique", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Alexandre Herculano", 1250, 239, "Lisboa", "Lisboa", "Santo António", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Dom Luís I", 1200, 204, "Lisboa", "Oeiras", "Misericórdia", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua do Ataíde", 1200, 383, "Lisboa", "Lisboa", "Misericórdia", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Travessa do Adro", 1150, 432, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Avenida Almirante Reis", 1150, 443, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Beco da Barbadela", 1100, 448, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Pátio Afonso de Albuquerque", 1100, 496, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Arco de Jesus", 1100, 666, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Tomás Ribeiro", 1050, 113, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Tomás Ribeiro", 1050, 264, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Andrade do Corvo", 1050, 458, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua dos Açores", 1000, 021, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Agostinho Lourenço", 1000, 623, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Arco do Cego", 1000, 159, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Brito Pais", 1495, 111, "Lisboa", "Oeiras", "Algés", "Lisboa");

insert into Nivel (Niv_Nome, Niv_descricao) values ("muito básico", "para iniciantes do treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("básico", "para pessoas que ainda não se sintam muito à vontade com o treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("médio", "para pessoas que já se sintam á vontade com o treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("avançado", "para pessoas que querem atingir o seu limite ");
insert into Nivel (Niv_Nome, Niv_descricao) values ("muito avançado", "para pessoas que querem exceder o seu limite");

insert into Categoria (Cat_Nome, Cat_descricao) values ("Funcional", "para um melhor movimento do corpo");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Dança", "se te apeteçer mexer e largar energia");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Corpo e Mente", "para um melhor equiliíbrio entre o corpo e a mente");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Cardio", "para melhorares a tua resitência e respiração");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Força", "para um desenvolvimento da massa muscular");

insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Gonçalo", "Feliciano", cast("2000.07.07" as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "gf@gmail.com", "M", 1);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Ricardo", "Vidigal", cast("2001.09.17" as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "RV@gmail.com", "M", 2);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Ana"," Alves", cast( "2002.04.03" as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "av@gmail.com", "F", 3);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("João"," Luz", cast("2001.03.30"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "escuro@gmail.com", "M", 4);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("André"," Costa", cast( "2000.07.17"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "andrepinguim@gmail.com", "M", 5);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Joana"," Macedo", cast( "2000.06.15"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "marianinha1999@gmail.com", "F", 6);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Mariana"," Vieira", cast("1995.05.23"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "ohhhvieiiraaa@gmail.com", "F", 7);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Margarida"," Barbosa", cast("1993.09.14"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "aflordapele@gmail.com", "F", 8);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("João"," Baptista", cast( "1970.02.11"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "quadradinhos@gmail.com", "M", 9);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Lionel"," Messi", cast("1970.09.03"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "ancaramessi@gmail.com", "M", 10);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Cristiano"," Ronaldo", cast("1990.03.27"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "siiiiiiii@gmail.com", "M", 11);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Cristovão"," Colombo", cast( "1983.01.16"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "velejar@gmail.com", "M", 12);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Sara"," Matos", cast("1963.08.12"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "imthebest@gmail.com", "F", 13);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Camila"," Florentino", cast( "1943.02.17"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "camila20flor@gmail.com", "F", 14);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Madalena"," Morgado", cast("1980.03.25"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "morgadex@gmail.com", "F", 15);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Bruna"," Mendes", cast( "1974.02.28"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "mendonçanum2@gmail.com", "F", 16);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Afonso"," Pires", cast( "1958.03.05"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "pedesefazfavor@gmail.com", "M", 17);
insert into utilizador (Use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Gustavo"," Belo", cast( "2002.08.09"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "omaisbelo@gmail.com", "M", 18);
insert into utilizador (Use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("José"," Caetano", cast( "1986.07.10"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()),  "caetano17auto@gmail.com", "M", 19);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("João"," Abrantes", cast( "2002.07.11"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "souoabrantes20@gmail.com", "M", 20);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Rita"," Lobo", cast( "2001.04.30"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "woooof@gmail.com", "F", 21);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Madalena"," Ferreira", cast( "1997.01.21"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "madaferras21@gmail.com", "F", 22);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Joana"," Almeida", cast( "1992.08.04"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "amaisbaixinha@gmail.com", "F", 23);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Paulo"," Azevedo", cast( "1965.04.06"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "paulinho1966@gmail.com", "M", 24);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Júlia"," Marcos", cast( "2000.03.25"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "benficaparasempre@gmail.com", "F", 25);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Margarida"," Duarte", cast("1995.09.10"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "margaduarte@gmail.com", "F", 26);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Raquel"," Leite", cast("2002.02.21"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "raquelleite@gmail.com", "F", 27);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Matilde"," Dias", cast( "1996.04.12"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "diassaodias@gmail.com", "F", 28);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Mariana"," Canedo", cast( "1984.08.31"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "canedo19@gmail.com", "F", 29);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("Guilherme"," Vidigal", cast( "1994.06.12"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "maninhofofinho@gmail.com", "M", 30);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_idade, use_email, use_sexo, use_Cod_id) values ("João"," Claro", cast( "1958.05.02"as date),TIMESTAMPDIFF(YEAR,use_birthday,CURDATE()), "benfica@gmail.com", "M", 31);

insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Manuel da Silva", "M", "manelidasilva@gmail.com",96843234, 1);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("José Carvalho", "M", "olhaocarvalho@gmail.com",923467980, 2);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Francisco Appleton", "M", "blocoesquerda@gmail.com",935672380, 3);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Joana Figueira", "F", "adorogatos@gmail.com",913652894, 4);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Alexandre Pato", "M", "arrozdepato@gmail.com",946217898, 5);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Filipa Casemiro", "F", "pipinhapt97@gmail.com",934528859, 6);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("João Castro", "M", "jcastropt@gmail.com",289567489, 7);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Madalena Fontes", "F", "madalenafpt89@gmail.com",281564321, 8);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Daniel Sota", "M", "dani96sota@gmail.com",96843234, 9);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Daniela Silva", "F", "danielaptsil@gmail.com",923467980, 10);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Filipa Lousa", "F", "pipalousa98@gmail.com",913652894, 11);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Rafael Matos", "M", "rafinha88@gmail.com",913652894, 12);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Teresa Oliveira", "F", "teresinhaoliv@gmail.com",923467980, 13);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Rui Caetano", "M", "ruicaetano17@gmail.com",96843234, 14);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Constança David", "F", "constancadavid@gmail.com",28567392, 15);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Maria Carolina", "F", "mariaabombar@gmail.com",218990385, 16);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Ricardo Veríssimo", "M", "verissimori@gmail.com",98345621, 17);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Jorge Vieira", "M", "jorgetattoo@gmail.com",98743264, 18);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Lucas Lima", "M", "brasillll@gmail.com",982145678, 19);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Fábio Neve", "M", "omaisbichopt@gmail.com",943257684, 20);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Bernardo Amado", "M", "pacotes@gmail.com",987234561, 21);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Carolina Cruzinha", "F", "ptcarolcruz@gmail.com",234556178, 22);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Joana Martins", "F", "joaninhamartins89@gmail.com",98743264, 23);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Clara Faustino", "F", "clarafaustinopt@gmail.com",943257684, 24);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Teresa Mota", "F", "teresinhavrumm@gmail.com",943257684, 25);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Bernardo Branco", "M", "daltonico19@gmail.com",913652894, 26);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Eliza Rusu", "F", "elizaptruzu@gmail.com",98743264, 27);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Francisca Ghira", "F", "ghiradegira@gmail.com",234571984, 28);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Diogo Amaro", "M", "amaropt@gmail.com",93462719, 29);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Rodrigo Freire", "M", "rodrifreire78@gmail.com",285642718, 30);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_contacto,Pt_Cod_id) values ("Inês Carvalho", "F", "inesptcarvalho@gmail.com",964321569, 31);

insert into Aula (Au_nome, Au_use_id, Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Yoga",1,1,1,1);
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Corpo e Mente",2,2,2,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Pilates",3,3,3,5); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Pilates Clínico",4,4,4,4); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Tai-chi",5,5,5,3); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Full Body",6,6,3,5); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Cycling",7,7,1,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Fit Boxe",8,8,1,1); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("HIIT",9,9,4,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Run",10,10,5,4); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Step",11,11,2,5); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Circuit Training",12,12,5,3); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Funcional",13,13,1,2);
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Body Pump",14,14,2,1);
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Abs",15,15,3,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Cross Training",16,16,1,3); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_id,Au_Niv_id) values ("Gap 30",17,17,5,4);
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("TRX",18,18,3,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Spartans",19,19,2,5); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Total Condicionamento",20,20,3,4); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Reeducação Postural",21,21,4,1); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Reabilitação Física",22,22,5,4); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Alongamentos",23,23,1,1); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Warrior",24,24,2,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Made in Brasil",25,25,5,3); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Airfit",26,26,4,5); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Zumba",27,27,2,1); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("X-Celerate",28,28,3,2); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Resistência",29,29,4,3); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Sprint",30,30,5,1); 
insert into Aula (Au_nome, Au_use_id,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Jump",31,31,2,5);

insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.00", cast("2021.01.16"as date), 1, 1);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "16.00", cast("2021.01.17"as date),2, 2);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "16.00", cast("2021.01.17"as date),3, 3);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "18.00", cast("2021.01.18"as date),4, 4);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "17.00", cast("2021.01.19"as date),5, 5);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Gulbenkian", "19.00", cast("2021.01.26"as date),6,6);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Mário Soares", "19.00", cast("2021.01.30"as date),7, 7);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Cerca das Graças", "18.30", cast("2021.02.01"as date),8, 8);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.45", cast("2021.01.25"as date),9, 9);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "18.45", cast("2021.01.23"as date),10, 10);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "16.00", cast("2021.01.14"as date),11, 11);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Ecológico de Monsanto", "16.00", cast("2021.01.24"as date),12, 12);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "17.15", cast("2021.02.08"as date),13, 13);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "16.45", cast("2021.01.15"as date),14, 14);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Calhau", "17.45", cast("2021.01.31"as date),15, 15);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "18.45", cast("2021.01.17"as date),16, 16);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "19.00", cast("2021.01.16"as date),17, 17);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Gulbenkian", "19.00", cast("2021.02.03"as date),18, 18);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "19.30", cast("2021.02.04"as date),19, 19);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Calhau", "19.30", cast("2021.02.06"as date),20, 20);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "16.45", cast( "2021.02.14"as date),21, 21);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "17.00", cast("2021.02.09"as date),22, 22);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "18.00", cast("2021.02.10"as date),23, 23);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "18.45", cast( "2021.02.02"as date),24, 24);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "16.15", cast("2021.02.11"as date),25, 25);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "17.30", cast("2021.02.05"as date),26, 26);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.30", cast("2021.02.07"as date),27, 27);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "19.00", cast("2021.02.21"as date),28, 28);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "17.15", cast("2021.02.22"as date),13, 29);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Cerca das Graças", "17.45", cast("2021.02.25"as date),30, 30);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Mário Soares", "16.00", cast("2021.02.12"as date),31, 31);

insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 1, 1); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 2, 2); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 3, 3); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 4, 4); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 5, 5); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 6, 6); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 7, 7); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 8, 8); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 9, 9);
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 10, 10); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 11, 11); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 12, 12); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 13, 13); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 14, 14); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 15, 15); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 16, 16); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 17, 17); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 18, 18); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 19, 19); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 20, 20); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 21, 21); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 22, 22); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 23, 23); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 24, 24); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 25, 25); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 27, 27); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 28, 28); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 29, 29); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 30, 30); 
insert into marcacao (mar_data, mar_use_id,mar_Au_id) values (cast("2021.02.13"as date), 31, 31); 

commit;