insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Avenida General Norton de Matos", "1495", 135, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Cândido de Figueiredo", "1500", 010, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Alameda Fernão Lopes", "1495", 169, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Abrantes Ferrão", "1600", 177, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Aboim Ascensão", "1700", 107, "Lisboa", "Lisboa", "Alvalade", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praceta A à Avenida Cidade Lourenço Marques", 1800, 033, "Lisboa", "Lisboa", "Parque das Nações", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Actor Isidoro", 1900, 190, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Acácio Barreiro", 1950, 172, "Lisboa", "Lisboa", "Marvilla", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Passeio das Musas", 1990, 122, "Lisboa", "Lisboa", "Parque das Nações", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Actor Epifânio", 1750, 124, "Lisboa", "Lisboa", "Lumiar", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Agostinho Neto", 1750, 315, "Lisboa", "Lisboa", "Lumiar", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Estrada de Benfica", 1500, 999, "Lisboa", "Lisboa", "São Domingos de Benfica", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Major Afonso Palla", 1495, 475, "Lisboa", "Oeiras", "Algés", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Calçada da Boa-Hora", 1300, 155, "Lisboa", "Lisboa", "Alcântara", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praça Afonso do Paço", 1350, 116, "Lisboa", "Lisboa", "Campo de Ourique", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Praça das Águas Livres ", 1250, 170, "Lisboa", "Lisboa", "Campo de Ourique", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Alexandre Herculano", 1250, 239, "Lisboa", "Lisboa", "Santo António", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Dom Luís I", 1200, 204, "Lisboa", "Oeiras", "Misericórdia", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua do Ataíde", 1200, 383, "Lisboa", "Lisboa", "Misericórdia", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Travessa do Adro", 1150, 432, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Avenida Almirante Reis", 1150, 443, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Beco da Barbadela", 1100, 448, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Pátio Afonso de Albuquerque", 1100, 496, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Arco de Jesus", 1100, 666, "Lisboa", "Lisboa", "Santa Maria Maior", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Tomás Ribeiro", 1050, 113, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Tomás Ribeiro", 1050, 264, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Andrade do Corvo", 1050, 458, "Lisboa", "Lisboa", "Avenidas Novas", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua dos Açores", 1000, 021, "Lisboa", "Lisboa", "Arroios", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Agostinho Lourenço", 1000, 623, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Arco do Cego", 1000, 159, "Lisboa", "Lisboa", "Areeiro", "Lisboa");
insert into codigo_postal (Cod_local, Cod_id_4D, Cod_id_3D, Cod_Cidade, Cod_Concelho, Cod_Freguesia, Cod_Distrito) values ("Rua Brito Pais", 1495, 111, "Lisboa", "Oeiras", "Algés", "Lisboa");

insert into Nivel (Niv_Nome, Niv_descricao) values ("muito básico", "para iniciantes do treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("básico", "para pessoas que ainda não se sintam muito à vontade com o treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("médio", "para pessoas que já se sintam á vontade com o treino");
insert into Nivel (Niv_Nome, Niv_descricao) values ("avançado", "para pessoas que querem atingir o seu limite ");
insert into Nivel (Niv_Nome, Niv_descricao) values ("muito avançado", "para pessoas que querem exceder o seu limite");

insert into Categoria (Cat_Nome, Cat_descricao) values ("Funcional", "para um melhor movimento do corpo");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Dança", "se te apeteçer mexer e largar energia");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Corpo e Mente", "para um melhor equiliíbrio entre o corpo e a mente");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Cardio", "para melhorares a tua resitência e respiração");
insert into Categoria (Cat_Nome, Cat_descricao) values ("Força", "para um desenvolvimento da massa muscular");

insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Gonçalo", "Feliciano", str_to_date("2000.07.07",'%Y.%m.%d'), "gf@gmail.com", "M", 135);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Ricardo", "Vidigal", str_to_date("2001.09.17",'%Y.%m.%d'), "RV@gmail.com", "M",239);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Ana"," Alves",str_to_date( "2002.04.03",'%Y.%m.%d'), "av@gmail.com", "F",116);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("João"," Luz", str_to_date("2001.03.30",'%Y.%m.%d'), "escuro@gmail.com", "M", 475);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("André"," Costa",str_to_date( "2000.07.17",'%Y.%m.%d'), "andrepinguim@gmail.com", "M",458);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Joana"," Macedo",str_to_date( "2000.06.15",'%Y.%m.%d'), "marianinha1999@gmail.com", "F",496);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Mariana"," Vieira", str_to_date("1995.05.23",'%Y.%m.%d'), "ohhhvieiiraaa@gmail.com", "F",443);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Margarida"," Barbosa", str_to_date("1993.09.14",'%Y.%m.%d'), "aflordapele@gmail.com", "F",111);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("João"," Baptista",str_to_date( "1970.02.11",'%Y.%m.%d'), "quadradinhos@gmail.com", "M",999);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Lionel"," Messi", str_to_date("1970.09.03",'%Y.%m.%d'), "ancaramessi@gmail.com", "M",190);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Cristiano"," Ronaldo", str_to_date("1990.03.27",'%Y.%m.%d'), "siiiiiiii@gmail.com", "M",010);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Cristovão"," Colombo",str_to_date( "1983.01.16",'%Y.%m.%d'), "velejar@gmail.com", "M",107);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Sara"," Matos", str_to_date("1963.08.12",'%Y.%m.%d'), "imthebest@gmail.com", "F",021);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Camila"," Florentino",str_to_date( "1943.02.17",'%Y.%m.%d'), "camila20flor@gmail.com", "F",111);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Madalena"," Morgado", str_to_date("1980.03.25",'%Y.%m.%d'), "morgadex@gmail.com", "F",623);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Bruna"," Mendes",str_to_date( "1974.02.28",'%Y.%m.%d'), "mendonçanum2@gmail.com", "F",458);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Afonso"," Pires",str_to_date( "1958.03.05",'%Y.%m.%d'), "pedesefazfavor@gmail.com", "M",239);
insert into utilizador (Use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Gustavo"," Belo",str_to_date( "2002.08.09",'%Y.%m.%d'), "omaisbelo@gmail.com", "M",170);
insert into utilizador (Use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("José"," Caetano",str_to_date( "1986.07.10",'%Y.%m.%d'),  "caetano17auto@gmail.com", "M",116);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("João"," Abrantes",str_to_date( "2002.07.11",'%Y.%m.%d'), "souoabrantes20@gmail.com", "M",315);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Rita"," Lobo",str_to_date( "2001.04.30",'%Y.%m.%d'), "woooof@gmail.com", "F",113);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Madalena"," Ferreira",str_to_date( "1997.01.21",'%Y.%m.%d'), "madaferras21@gmail.com", "F",172);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Joana"," Almeida",str_to_date( "1992.08.04",'%Y.%m.%d'), "amaisbaixinha@gmail.com", "F",113);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Paulo"," Azevedo",str_to_date( "1965.04.06",'%Y.%m.%d'), "paulinho1966@gmail.com", "M",155);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Júlia"," Marcos",str_to_date( "2000.03.25",'%Y.%m.%d'), "benficaparasempre@gmail.com", "F",475);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Margarida"," Duarte", str_to_date("1995.09.10",'%Y.%m.%d'), "margaduarte@gmail.com", "F",315);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Raquel"," Leite", str_to_date("2002.02.21",'%Y.%m.%d'), "raquelleite@gmail.com", "F",122);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Matilde"," Dias",str_to_date( "1996.04.12",'%Y.%m.%d'), "diassaodias@gmail.com", "F",021);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Mariana"," Canedo",str_to_date( "1984.08.31",'%Y.%m.%d'), "canedo19@gmail.com", "F",496);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("Guilherme"," Vidigal",str_to_date( "1994.06.12",'%Y.%m.%d'), "maninhofofinho@gmail.com", "M",239);
insert into utilizador (use_nomeP, use_nomeA, use_birthday, use_email, use_sexo, use_Cod_id_3D) values ("João"," Claro",str_to_date( "1958.05.02",'%Y.%m.%d'), "benfica@gmail.com", "M",159);

insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Manuel da Silva", "M", "manelidasilva@gmail.com", 458);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("José Carvalho", "M", "olhaocarvalho@gmail.com",239);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Francisco Appleton", "M", "blocoesquerda@gmail.com",170);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Joana Figueira", "F", "adorogatos@gmail.com",116);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Alexandre Pato", "M", "arrozdepato@gmail.com",315);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Filipa Casemiro", "F", "pipinhapt97@gmail.com",172);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("João Castro", "M", "jcastropt@gmail.com",113);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Madalena Fontes", "F", "madalenafpt89@gmail.com",155);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Daniel Sota", "M", "dani96sota@gmail.com",475);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Daniela Silva", "F", "danielaptsil@gmail.com",315);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Filipa Lousa", "F", "pipalousa98@gmail.com",122);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Rafael Matos", "M", "rafinha88@gmail.com",021);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Teresa Oliveira", "F", "teresinhaoliv@gmail.com",496);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Rui Caetano", "M", "ruicaetano17@gmail.com",239);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Constança David", "F", "constancadavid@gmail.com",107);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Maria Carolina", "F", "mariaabombar@gmail.com",623);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Ricardo Veríssimo", "M", "verissimori@gmail.com",010);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Jorge Vieira", "M", "jorgetattoo@gmail.com",135);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Lucas Lima", "M", "brasillll@gmail.com",496);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Fábio Neve", "M", "omaisbichopt@gmail.com",999);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Bernardo Amado", "M", "pacotes@gmail.com",170);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Carolina Cruzinha", "F", "ptcarolcruz@gmail.com",111);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Joana Martins", "F", "joaninhamartins89@gmail.com",190);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Clara Faustino", "F", "clarafaustinopt@gmail.com",116);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Teresa Mota", "F", "teresinhavrumm@gmail.com",021);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Bernardo Branco", "M", "daltonico19@gmail.com",107);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Eliza Rusu", "F", "elizaptruzu@gmail.com",458);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Francisca Ghira", "F", "ghiradegira@gmail.com",623);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Diogo Amaro", "M", "amaropt@gmail.com",458);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Rodrigo Freire", "M", "rodrifreire78@gmail.com",383);
insert into Personal_Trainer (Pt_nome, Pt_sexo, Pt_email,Pt_Cod_id_3D) values ("Inês Carvalho", "F", "inesptcarvalho@gmail.com",107);

insert into Aula (Au_nome, Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Yoga",1,1,1);
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Corpo e Mente",2,2,2); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Pilates",3,3,5); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Pilates Clínico",4,4,4); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Tai-chi",5,5,3); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Full Body",6,3,5); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Cycling",7,1,2); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Fit Boxe",8,1,1); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("HIIT",9,4,2); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Run",10,5,4); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Step",1,2,5); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Circuit Training",12,5,3); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Funcional",13,1,2);
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Body Pump",14,2,1);
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Abs",15,3,2); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Cross Training",16,1,3); 
insert into Aula (Au_nome,Au_Pt_id,Au_Cat_id,Au_Niv_id) values ("Gap 30",17,5,4);
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("TRX",18,3,2); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Spartans",19,2,5); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Total Condicionamento",20,3,4); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Reeducação Postural",21,4,1); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Reabilitação Física",22,5,4); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Alongamentos",23,1,1); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Warrior",24,2,2); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Made in Brasil",25,5,3); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Airfit",26,4,5); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Zumba",27,2,1); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("X-Celerate",28,3,2); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Resistência",29,4,3); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Sprint",30,5,1); 
insert into Aula (Au_nome,Au_Pt_id, Au_Cat_ID, Au_Niv_id) values ("Jump",31,2,5);

insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.00", str_to_date("2021.01.16",'%Y.%m.%d'), 1, 1);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "16.00", str_to_date("2021.01.17",'%Y.%m.%d'),2, 2);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "16.00", str_to_date("2021.01.17",'%Y.%m.%d'),3, 3);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "18.00", str_to_date("2021.01.18",'%Y.%m.%d'),4, 4);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "17.00", str_to_date("2021.01.19",'%Y.%m.%d'),5, 5);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Gulbenkian", "19.00", str_to_date("2021.01.26",'%Y.%m.%d'),6,6);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Mário Soares", "19.00", str_to_date("2021.01.30",'%Y.%m.%d'),7, 7);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Cerca das Graças", "18.30", str_to_date("2021.02.01",'%Y.%m.%d'),8, 8);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.45", str_to_date("2021.01.25",'%Y.%m.%d'),9, 9);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "18.45", str_to_date("2021.01.23",'%Y.%m.%d'),10, 10);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "16.00", str_to_date("2021.01.14",'%Y.%m.%d'),11, 11);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Ecológico de Monsanto", "16.00", str_to_date("2021.01.24",'%Y.%m.%d'),12, 12);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "17.15", str_to_date("2021.02.08",'%Y.%m.%d'),13, 13);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "16.45", str_to_date("2021.01.15",'%Y.%m.%d'),14, 14);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Calhau", "17.45", str_to_date("2021.01.31",'%Y.%m.%d'),15, 15);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "18.45", str_to_date("2021.01.17",'%Y.%m.%d'),16, 16);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "19.00",str_to_date("2021.01.16",'%Y.%m.%d'),17, 17);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Gulbenkian", "19.00", str_to_date("2021.02.03",'%Y.%m.%d'),18, 18);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "19.30", str_to_date("2021.02.04",'%Y.%m.%d'),19, 19);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Calhau", "19.30", str_to_date("2021.02.06",'%Y.%m.%d'),20, 20);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Recreativo do Alvito", "16.45",str_to_date( "2021.02.14",'%Y.%m.%d'),21, 21);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Floresta de Monsanto", "17.00", str_to_date("2021.02.09",'%Y.%m.%d'),22, 22);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "18.00", str_to_date("2021.02.10",'%Y.%m.%d'),23, 23);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "18.45",str_to_date( "2021.02.02",'%Y.%m.%d'),24, 24);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Estrela", "16.15", str_to_date("2021.02.11",'%Y.%m.%d'),25, 25);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "17.30", str_to_date("2021.02.05",'%Y.%m.%d'),26, 26);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque Eduardo VII", "16.30", str_to_date("2021.02.07",'%Y.%m.%d'),27, 27);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Tapada das Necessidades", "19.00", str_to_date("2021.02.21",'%Y.%m.%d'),28, 28);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Parque do Penedo", "17.15", str_to_date("2021.02.22",'%Y.%m.%d'),13, 29);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim da Cerca das Graças", "17.45", str_to_date("2021.02.25",'%Y.%m.%d'),30, 30);
insert into qualificado (qual_local, qual_horario, qual_dataderealizacao, qual_Au_id, qual_Pt_id) values ("Jardim Mário Soares", "16.00", str_to_date("2021.02.12",'%Y.%m.%d'),31, 31);

insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 1, 1); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 2, 2); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 3, 3); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 4, 4); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 5, 5); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 6, 6); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 7, 7); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 8, 8); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 9, 9); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 10, 10); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 11, 11); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 12, 12); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 13, 13); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 14, 14); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 15, 15); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 16, 16); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 17, 17); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 18, 18); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 19, 19); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 20, 20); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 21, 21); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 22, 22); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 23, 23); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 24, 24); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 25, 25); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 27, 27); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 28, 28); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 29, 29); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 30, 30); 
insert into pagar (pag_data, pag_quantidade, pag_tax_pag, pag_use_id,pag_Pt_id) values (str_to_date("2021.02.13",'%Y.%m.%d'), "30", "30", 31, 31); 

commit;